/** Textos de UI del flujo guiado (navegación, notificaciones, aria). */

export const COPY = {
  inspiration: {
    heroTitle: 'Inspiración',
    heroTitleAccent: 'Elige de dónde nace tu paleta',
    heroSubtitle: 'Cuatro caminos para empezar. Teoría, imagen, concepto o tendencia.',
    trendingLabel: 'Paletas en tendencia',
    backToMenu: 'Volver al menú',
    archetypesMenuTitle: '¿Cómo quieres inspirarte?',
    archetypesMenuSubtitle: 'Elige entre explorar conceptos o formas abstractas',
  },
  nav: {
    back: 'Volver',
    backToApplication: 'Volver a Aplicación',
    nextToApplication: 'Siguiente: Aplicación',
    nextToAnalysis: 'Siguiente: Análisis',
    savePalette: 'Guardar paleta',
  },
  banner: {
    moreOptions: 'Más opciones',
    moreOptionsAria: 'Más opciones (Guardar, Deshacer, Rehacer, Candado)',
    closeOptions: 'Cerrar opciones',
    savePalette: 'Guardar en mi perfil',
    undo: 'Deshacer',
    redo: 'Rehacer',
    lockOff: (sectionName: string) => `Zona segura: Bloquea el historial de cambios hasta ahora. Se desbloquea al salir de ${sectionName}.`,
    lockOn: 'Desbloquear deshacer',
    lockAriaOff: 'Bloquear deshacer',
    lockAriaOn: 'Desbloquear deshacer',
    restoreInSection: 'Restaurar la paleta al estado al entrar en esta sección',
    history: 'Historial de cambios',
    historyAria: 'Ver historial de cambios',
  },
  historyModal: {
    title: 'Historial de cambios',
    subtitle: 'Haz clic en una versión para restaurar la paleta en ese punto.',
    initialLabel: 'Estado inicial',
    numberLabel: (n: number) => `#${n}`,
    sectionRefinement: 'Refinar',
    sectionApplication: 'Aplicar',
    sectionAnalysis: 'Análisis',
    close: 'Cerrar',
    removeEntry: 'Eliminar este paso del historial',
  },
  saveModal: {
    title: 'Guardar paleta',
    nameLabel: 'Nombre de la paleta',
    namePlaceholder: 'Ej. Mi paleta de proyecto',
    profileNote: 'La paleta guardada podrá verse en tu perfil.',
    cancel: 'Cancelar',
    save: 'Guardar',
    sectionRefinement: 'Refinar',
    sectionApplication: 'Aplicar',
    sectionAnalysis: 'Análisis',
    versionLabel: (n: number) => `Versión ${n}`,
  },
  notifications: {
    paletteRestored: '↩ Paleta inicial restaurada',
    colorsShuffled: '🔀 Colores mezclados',
    addPaletteName: '⚠️ Añade un nombre a tu paleta',
    paletteSaved: '✅ ¡Paleta guardada!',
    correctionApplied: '✅ Corrección aplicada',
    changesApplied: '✅ Cambios aplicados',
    colorAdded: '➕ Color añadido',
    colorRemoved: '➖ Color eliminado',
    loaded: (name: string) => `📂 Cargada: ${name}`,
    loadedForExport: (name: string) => `📂 Cargada para exportar: ${name}`,
    removed: (name: string) => `🗑️ Eliminada: ${name}`,
  },
  application: {
    title: 'Aplicación',
    subtitle: 'Vista previa de tu paleta en distintos contextos y formatos.',
    primaryAction: 'Mejorar paleta →',
    restoreLabel: 'Reiniciar',
    restoreConfirmTitle: '¿Reiniciar cambios de Aplicar?',
    restoreConfirmMessage: 'Se desharán todos los cambios hechos en esta sección desde la última vez que entraste. Si quieres reiniciar la paleta a su estado original antes de cualquier edición puedes hacerlo desde el botón "Reiniciar" en la sección Refinar.',
    restoreConfirmCancel: 'Cancelar',
    restoreConfirmOk: 'Reiniciar',
    restoreNotification: '↩ Cambios en Aplicar restaurados',
  },
  refinement: {
    backAria: 'Volver a la fase anterior',
    back: 'Volver',
    title: 'Refina tu paleta',
    subtitle: 'Ajusta colores, orden y aplica cambios a toda la paleta.',
    primaryAction: 'Mejorar paleta →',
    restoreLabel: 'Reiniciar',
    restoreInitial: 'Restaurar',
    restoreInitialAria: 'Restaurar paleta al estado original al entrar en Refinar',
    restoreConfirmTitle: '¿Reiniciar la paleta?',
    restoreConfirmMessage: 'Se restaurará la paleta a su estado original (con el que accediste a Refinar por primera vez) y se desharán todos los cambios realizados en cualquier sección (Refinar, Aplicar, etc.). Se borrará el historial de deshacer/rehacer.',
    restoreConfirmCancel: 'Cancelar',
    restoreConfirmOk: 'Reiniciar',
    undo: 'Deshacer',
    redo: 'Rehacer',
    shuffle: 'Mezclar orden de colores',
    shuffleButton: 'Mezclar',
  },
} as const;
